version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[GH Actions]"
    open-pull-requests-limit: 5
    # reviewers:
    #   - [GITHUB_USER_NAME]

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[npm]"
      prefix-development: "[npm dev]"
    open-pull-requests-limit: 10
    # reviewers:
    #  - [GITHUB_USER_NAME]
    pull-request-branch-name:
      separator: "-"

